# This file is a template - actual key content will be injected by apply-secrets.sh
# DO NOT manually edit this file with actual key content
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-public-key
  namespace: swlabpods
data: {}
  # id_rsa.pub: <will be populated by script>
