# This file is a template - actual key content will be injected by apply-secrets.sh
# DO NOT manually edit this file with actual key content
apiVersion: v1
kind: Secret
metadata:
  name: backend-ssh-key
  namespace: swlabpods
type: Opaque
data: {}
  # id_rsa: <will be populated by script>
  # id_rsa.pub: <will be populated by script>
